stages:
  - test
  - build

image: node:12.16-stretch-slim

cache:
  key: dependencies
  paths:
    - .npm/
    - node_modules/

eslint:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npm install
  script:
    - npm run lint
  only:
    - master
    - merge_requests

test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npm install
  script:
    - npm run test
  only:
    - master
    - merge_requests

build-docker-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - master
